### ISSUE TITLE
Switch Sonar static analysis scans to CI

### ISSUE THREAD

**Issue by e271828-** [hCaptcha/hcaptcha-android-sdk#52]
- [x] token secret added to repo
- [x] Update build.gradle file with the org.sonarqube plugin and its configuration:
```
plugins {
  id "org.sonarqube" version "3.4.0.2513"
}

sonarqube {
  properties {
    property "sonar.projectKey", "hCaptcha_hcaptcha-android-sdk"
    property "sonar.organization", "hcaptcha"
    property "sonar.host.url", "https://sonarcloud.io"
  }
}
```
- [x] update `.github/workflows/build.yml`

Base configuration to run a SonarCloud analysis on your master branch and Pull Requests below. We already have some GitHub Actions, so want to just add some of these new steps.

```
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info
```

- [ ] flip switch on sonarcloud config dash.
